services:
  spark-master:
    image: bitnami/spark:3.5.4
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_NO_DAEMONIZE=false
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_MASTER_PORT=7077
    volumes:
      - ./word_count.py:/opt/word_count.py
    ports:
      - "7077:7077" # Spark master port
      - "8080:8080" # Spark master web UI
    # command: >
    #   bash -c "$SPARK_HOME/sbin/start-master.sh && tail -f /dev/null"

  spark-worker-1:
    image: bitnami/spark:3.5.4
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_NO_DAEMONIZE=false
    ports:
      - "8081:8081" # (optional) Expose web UI of worker
    # command: >
    #   bash -c "$SPARK_HOME/sbin/start-worker.sh $SPARK_MASTER_URL && tail -f /dev/null"

  spark-worker-2:
    image: bitnami/spark:3.5.4
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_NO_DAEMONIZE=false
    ports:
      - "8082:8081" # optional
    # command: >
    #   bash -c "$SPARK_HOME/sbin/start-worker.sh $SPARK_MASTER_URL && tail -f /dev/null"
